import Head from 'next/head'
import Image from 'next/image'

import Layout from '../components/Layout.js'

export default function Page() {
  return (
    <Layout>
      <Head>
        <title>WebTech - contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="wt-title">
        Contact
      </h1>
      <form className="block">
        <div>
          <label>
            <span>First name</span>
            <input type="text" name="firstname" />
          </label>
        </div>
        <div>
          <label>
            <span>Last name</span>
            <input type="text" name="lastname" />
          </label>
        </div>
        <div>
          <label>
            <span>Email</span>
            <input type="text" name="email" />
          </label>
        <div>
        </div>
          <label>
            <span>Message</span>
            <textarea name="message" />
          </label>
        </div>
        <button type="submit" class="bg-gray-200 placeholder-gray-400 text-gray-800 font-bold py-2 px-4 rounded">
        Submit
        </button>

      </form>
    </Layout>
  )
}
